### ISSUE TITLE
GPL or LGPL?

### ISSUE THREAD

**Issue by i3games** [molleindustria/p5.play#1]
p5.play.js refers to GPL: "This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.", but licence.txt contains LGPL.

**Comment by toolness** [comment]
Hmm, good question @i3games... It looks like p5.js uses the LGPL too, but it doesn't include any mention of its license in the JS library, and neither do p5.dom.js or p5.sound.js. So if we want to follow suit, we can just remove the license information from p5.play.js, and leave the `license.txt` file.

@molleindustria can you confirm that we want to use LGPL here, rather than GPL? If that's correct, I can go ahead and make everything consistent.

**Comment by molleindustria** [comment]
Yes, I don't remember what happened there. In general I prefer GPL but it makes more sense to be consistent with p5.js

**Comment by nickmcintyre** [comment]
@quinton-ashley I'm looking into using p5.play as part of a visual novel engine and am a bit confused about licensing. [package.json](https://github.com/molleindustria/p5.play/blob/4d571bfb3eb5ffb1a8f1f2dd39d9a39e7f6492ae/package.json#L11) refers to the LGPL v2.1 while the [source code](https://github.com/molleindustria/p5.play/blob/4d571bfb3eb5ffb1a8f1f2dd39d9a39e7f6492ae/p5.play.js#L7) mentions GPL v3 -- mind clarifying?

**Comment by quinton-ashley** [comment]
Sounds great! I updated the license to GPL v3!

**Comment by nickmcintyre** [comment]
Thanks!
