### ISSUE TITLE
P5 Play Groups...

### ISSUE THREAD

**Issue by mtareiling** [molleindustria/p5.play#134]
Hello im trying to build a game and im getting stuck ad the part where i need groups. so i decided to google "p5 play groups"but the only useful thing i could find was the examples but i think those aren't working anymore because i tried them. so can someone PLEASE explain how the groups work and what i haev to do.

**Comment by islemaster** [comment]
Hi there @mtareiling!

In p5.play, groups are [JavaScript arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) but with a number of special, p5.play-specific abilities.  Here's the official documentation for groups, and some working examples:

- [Group API documentation](http://molleindustria.github.io/p5.play/docs/classes/Group.html)
- [Sprite Group example](http://molleindustria.github.io/p5.play/examples/index.html?fileName=sprite8.js)
- [Collisions between groups example](http://molleindustria.github.io/p5.play/examples/index.html?fileName=collisions2.js)

The general pattern for using groups is to create a group, `add()` your sprites to that group, then do things with the whole group at once, rather than with individuals.

```javascript
var myGroup;

function setup() {
  createCanvas(800,400);  

  // Create an empty group
  myGroup = new Group();
  
  // Create six sprites and add them to the group
  for (var i = 0; i < 6; i++) {
    var newSprite = createSprite(100 * i, 0);
    myGroup.add(newSprite);
  }
}

function draw() {
  // a group can be accessed just like an array
  // the removed objects will be automatically removed from the groups as well
  for (var i = 0; i < myGroup.length; i++) {
    myGroup[i].rotation += 1;
  }

  // You can draw just one group of sprites instead of all sprites
  background('white');  
  drawSprites(myGroup);
}
```

Finally, when you destroy a sprite with `sprite.remove()` or it expires from using `sprite.lifetime`, it is automatically removed from all the groups it was a part of.

I hope that helps!
Brad

**Comment by mtareiling** [comment]
Thnx youre the best!
