### ISSUE TITLE
Sprite sheets not working correctly with p5.js >= v0.5.5

### ISSUE THREAD

**Issue by cesarrodas** [molleindustria/p5.play#136]
I don't know if this is my mistake or if the documentation is behind but I cannot get
the loadSpriteSheet method to work properly. I tried making a json specifying the x and y of the frame, but instead the same frame is chosen and displaced by the x amount. The same thing happens with the short
version where you choose height width and number of frames. the same first frame is chosen and displaced by the x amount.
I couldn't find the issue if it already exists.

**Comment by cesarrodas** [comment]
Hey I would like to put an example, maybe someone will be able to help
My code: https://github.com/cesarrodas/ghost
The live example: http://powerful-reaches-15768.herokuapp.com/

**Comment by islemaster** [comment]
Hi there @cesarrodas.  The problem you're describing is probably due to an API change in p5.js 0.5.5 that altered the argument order of the `image()` function, which our spritesheet code depends on.  The issue (and a possible fix) is described in https://github.com/molleindustria/p5.play/pull/132.

We haven't merged this fix yet becaue p5.play is currently built on p5.js v0.5.4, which uses the old argument order.  My preferred path forward would be to document the current dependency on p5.js <= v0.5.4, then carefully upgrade everything to require >= v0.5.5.  That's going to take some time, since we're all part-time volunteer contributors :grin:.

For your own project, there are two ways to be immediately unblocked:

- Downgrade p5.js to v0.5.4 (a copy is included in the [examples/lib directory](https://github.com/molleindustria/p5.play/tree/master/examples/lib) of this repository)
- Apply the change in https://github.com/molleindustria/p5.play/pull/132 to your copy of p5.play.

Thank you for bringing this to our attention!  I'm changing the name of your issue to be a little more specific and am leaving this open while we get the version incompatibility problem resolved.

**Comment by islemaster** [comment]
I've opened a change for review that should make p5.play compatible with the latest version of p5.js and fix the issue you've described here.  Please take a look!
https://github.com/molleindustria/p5.play/pull/140

**Comment by cesarrodas** [comment]
Awesome! Great to hear I was able to help, I wasn't 100% on it being the library or if my use was outdated. 
Looking forward to trying it in my free time :+1:

**Comment by islemaster** [comment]
Let's leave it open until the fix is merged.

**Comment by cesarrodas** [comment]
I know this isn't the right place but i don't know if there is a forum about this or not. 
I created a tree sprite and a player sprite. the tree sprite gets destroyed and replaced every loop so that i can save some memory as the map gets bigger and the tree goes off screen. the problem that i'm having is the tree always shows up on top of the player. any way I can update the player to be redrawn once they are under the trees y value? the draw and update methods don't seem to do what i want. again i know this probably doesn't belong here and i can erase it if it displeases someone.  thanks

**Comment by SnipedCode** [comment]
Is there a fix ?  to this problem ?

**Comment by brianjschott** [comment]
@SnipedCode thanks so much for your suggestion, it worked perfectly. This fix really should be merged!

**Comment by mihalski** [comment]
@SnipedCode The fix provided doesn't work for me with the following code. I still need to go back to v0.5.4 to make it work.

```js
let tile_sprite_sheet;

function preload() {
    tile_sprite_sheet = loadSpriteSheet('assets/tiles_spritesheet.png', 72, 72, 200);
}

function setup() {
    createCanvas(640, 480);
}

function draw() {
    tile_sprite_sheet.drawFrame(169, 100, 100);
}
```
The timesheet used is from one of the examples. https://molleindustria.github.io/p5.play/examples/assets/tiles_spritesheet.png
