### ISSUE TITLE
Rotate collider with Sprite

### ISSUE THREAD

**Issue by a1steaksauce** [molleindustria/p5.play#142]
Hello,
I am working with the current p5.play.js version, and I noticed that it is currently impossible to rotate collision boxes.
However, I noticed that https://code-dot-org.github.io/p5.play/docs/files/lib_p5.play.js.html is a version of p5.play that HAS oriented bounding boxes. 
I was wondering why OBBs are not currently implemented in p5.play and whether that will change in the future.

On a side note, I am trying to rotate bounding boxes to fit the sprite image better. Is there a way to do this using the new p5.play.js?

Current code for creating the objects:

`        
         var post = createSprite(x, y);
         post.draw = () => {rect(0, 0, 10, 50);}
         post.rotation = 45; 
         post.immovable = true;
         post.setCollider("rectangle", 0, 0, 10, 50);
         post.debug = true;
`

Bounding boxes with the old version at https://code-dot-org.github.io/p5.play/docs/files/lib_p5.play.js.html:

![Bounding boxes with the old version at https://code-dot-org.github.io/p5.play/docs/files/lib_p5.play.js.html](https://user-images.githubusercontent.com/15972020/29034439-42a4351e-7b66-11e7-988f-6fd668564f6c.png)

Bounding boxes with the current version in this repository:

![Bounding boxes with the current version in the repository](https://user-images.githubusercontent.com/15972020/29034441-4533c16e-7b66-11e7-810f-903e18bd5359.png)

**Comment by islemaster** [comment]
Hi @worcestershire!  Good question.

It's not a question of older and newer - you've been looking at docs for a p5.play [fork](https://help.github.com/articles/github-glossary/#fork), a "remix" of this engine maintained by [Code.org](https://code.org) for use [on their site](https://code.org/educate/gamelab).  The matching documentation for this main project can be found at https://molleindustria.github.io/p5.play/docs/. Unfortunately the main p5.play project has never had support for Oriented Bounding Boxes.

I work on both this main project and the Code.org fork.  We haven't rolled OBBs back into the main project because they depend on a big rewrite of the collision logic that's likely to break older p5.play projects.  They also slow the engine down a bit and introduce some complexity that the core p5.play project doesn't want - one of our goals is to keep the engine source accessible for beginners.

We may get around to implementing OBBs in the main project somewhere down the road, but if/when we do it will probably be a simpler approach.  In the meantime, you're always welcome to [use the Code.org version of p5.play](https://github.com/code-dot-org/p5.play) for your project - it's also actively mantained and licenced under the GNU GPL.

Thanks for asking!

**Comment by molleindustria** [comment]
Hi @islemaster , is there a reason why code.org forked at some point. Did I miss that conversation? 😳

**Comment by islemaster** [comment]
Hi @molleindustria!  I believe we started using a fork back in October 2016 just for the sake of velocity - it's helpful to make changes/fixes in our own copy and use them right away, while we get things properly reviewed here on the main project.

We didn't diverge much until our curriculum team asked for a pretty significant overhaul of the collision system, including support for OBBs and some breaking changes to the meanings of `collide` and `displace`.  You can [review that change here](https://github.com/code-dot-org/p5.play/pull/12) - it's a huge diff, and I didn't propose it upstream both because we didn't have all the [bugs](https://github.com/code-dot-org/p5.play/pull/18) and [performance issues](https://github.com/code-dot-org/p5.play/pull/24) worked out and because you and I [had already discussed some subset of those changes](https://github.com/molleindustria/p5.play/pull/114) that didn't seem like a good fit for the main project.

Outside of collision code we're fairly in-sync with p5.play and I still pull fixes across both ways whenever I can.  We also try to make sure we point people back to the main project here - it's called out at the [top of our README](https://github.com/code-dot-org/p5.play/blob/master/README.md) and we version [with a `-cdo` suffix](https://github.com/code-dot-org/p5.play/releases) and [under the `@code-dot-org/` namespace on npm](https://www.npmjs.com/package/@code-dot-org/p5.play).  From this discussion it sounds like we should make sure to make a note clearly visible in the published documentation too - sorry about that, I'll take care of it today.

I'd be happy to propose some of our collision changes here so we can revisit that that discussion.  Now that the dust has settled on our fork we've got some nice new features (like OBBs) and I can probably separate those from some of the semantic changes to collide/displace that we don't want here.  It's :100: in Code.org's interest to be more in sync with the main project, so that could be a win-win :+1:.  Some of the collision code has changed significantly, but I think that's always been one of the tricker parts of the library for beginners anyway, and it's stayed easy to use.

Here are some highlights of our changes - take a look and see if you think this makes the library too complicated, or if any of it could work well in the main project.

- [`Sprite.setCollider`](https://github.com/code-dot-org/p5.play/blob/9a30d948feeae0146857407645993f45cd8fd067/lib/p5.play.js#L1448-L1534) has a lot more options and nice defaults if you just want to call `setCollider('circle')` or `setCollider('rectangle')`.
- A lot of the tricky logic of sprite collision has been broken out into a [`_collideWithOne`](https://github.com/code-dot-org/p5.play/blob/9a30d948feeae0146857407645993f45cd8fd067/lib/p5.play.js#L2209-L2316) helper (group collisions are handled nicely in an outer layer) and [`_findDisplacement`](https://github.com/code-dot-org/p5.play/blob/9a30d948feeae0146857407645993f45cd8fd067/lib/p5.play.js#L2318-L2395) helper - I'd want to be really careful moving this stuff, as it's where semantic changes to `collide`/`displace` live.
- A [`CollisionShape`](https://github.com/code-dot-org/p5.play/blob/9a30d948feeae0146857407645993f45cd8fd067/lib/p5.play.js#L3958-L4392) base class  and the [`PointCollider`](https://github.com/code-dot-org/p5.play/blob/9a30d948feeae0146857407645993f45cd8fd067/lib/p5.play.js#L4394-L4435), [`CircleCollider`](https://github.com/code-dot-org/p5.play/blob/9a30d948feeae0146857407645993f45cd8fd067/lib/p5.play.js#L4437-L4640), [`AxisAlignedBoundingBoxCollider`](https://github.com/code-dot-org/p5.play/blob/9a30d948feeae0146857407645993f45cd8fd067/lib/p5.play.js#L4642-L4875) and [`OrientedBoundingBoxCollider`](https://github.com/code-dot-org/p5.play/blob/9a30d948feeae0146857407645993f45cd8fd067/lib/p5.play.js#L4877-L5132) handle bounding boxes and overlap/displacement calculations, and let us eliminate a lot of special cases in the collision logic.  They can also be completely ignored by beginners, since `Sprite.setCollider()` does everything you need at first.
- A [`Transform2D`](https://github.com/code-dot-org/p5.play/blob/9a30d948feeae0146857407645993f45cd8fd067/lib/p5.play.js#L5134-L5419) class is used internally by the collision shapes, which helps with performance and lets us apply composed sprite transformations (scaled+rotated+offset) to the collider correctly.  Can also be totally ignored by beginners - I feel like this falls into the same category as the existing Quadtree, as a fairly opaque helper to the library.

Sorry for not communicating all this better and sooner.  I hope I haven't offended you by doing a fair amount of work in our fork that hasn't come back upstream.

**Comment by molleindustria** [comment]
This is all fantastic. I should probably start a new discussion thread but I was wondering if I should just deprecate the original repository and point to the code.org one since you folks have been de facto developing it since the first release. 
I'm definitely not attached to the collision logic and semantic, especially if the new system handles oriented bounding boxes (which has been a frequent request). And the noble idea of maintaining the source as simple as possible is not even in line with p5 approach, which has pretty arcane stuff under the hood.
What I'm wondering is: are you planning on keeping the library modular and usable with the future versions of p5 independently from the code.org tools? 
Can you think of any reasons why this *wouldn't* be a good idea?

**Comment by islemaster** [comment]
Personally I would pull the collision changes back into the main project rather than deprecate in favor of the Code.org fork.  There has been an open [Forge a Release Process](https://github.com/molleindustria/p5.play/issues/25) issue on this repo for a while - maybe we formally tag what's currently here as 1.0 and then release the new collision behaviors as 1.1.

- code-dot-org/p5.play is 145 ahead/31 behind, so there _are_ some changes and fixes that hasn't been pulled into the Code.org fork. (Speaking of, can I get a review of https://github.com/molleindustria/p5.play/pull/140?)
- I'm committed to keeping our fork modular and reusable, but we've already made some small changes to keep it _compatible_ with our tools (hooks for our JavaScript sandbox, for example) and I can't promise our curriculum team won't want more breaking changes down the road.
- The last two weeks of traffic suggest this main repository is still by far the most used.
  - [molleindustria/p5.play](https://github.com/molleindustria/p5.play/graphs/traffic): 771 views / 184 unique visitors.
  - [code-dot-org/p5.play](https://github.com/code-dot-org/p5.play/graphs/traffic): 7 views / 5 unique visitors.

**Comment by quinton-ashley** [comment]
I'm creating a new version of p5.play that uses planck.js behind the scenes, which is very fast. p5.play v3 will hopefully be better than code.org's fork of p5.play. Here's an example of sprite rotation collision:
https://molleindustria.github.io/p5.play/examples/v3.html?fileName=drop.js
