### ISSUE TITLE
Touch events

### ISSUE THREAD

**Issue by paulloz** [molleindustria/p5.play#15]
Hi!
p5 mouse events seem to work quite well on mobile / tablets (i.e. [touchEnded](http://p5js.org/reference/#/p5/touchEnded) falls back to [mouseReleased](http://p5js.org/reference/#/p5/mouseReleased) if not defined). However p5.play does not seem to handle touch events.
Am I right? Is this planned in a near future? (Would be a great addition to p5.play).

**Comment by toolness** [comment]
Hmm, good question--is there a particular kind of touch API you'd like to see that isn't already offered by core p5.js? For instance, the mouse and keyboard APIs of p5.play all seem to improve upon the ones offered by core p5.js in some way--I'm just curious what an improved touch API might look like.

Or, alternatively, do you mean that you'd like to see the mouse API provided by p5.play fall-back to touch events if no mouse is present? So that e.g. `mouseDown(LEFT)` returns `true` if the user is touching the touch-screen and has no mouse on their device?

**Comment by molleindustria** [comment]
The main addition in p5.play are functions like mouseWentDown that check whether the input changed since the last frame. These are useful for certain game programming patterns in which using separate functions to detect events is annoying. 
I see now that the p5.play mouse example doesn't work on iOS, while the p5.js mousePressed() does so probably there is something that can be done there.

**Comment by karneaud** [comment]
+1

**Comment by karneaud** [comment]
If I had to try and implement this myself....where should I start?

**Comment by molleindustria** [comment]
This issue depended on p5.js handling of touch input and has been addressed by updating the library in examples. 
I find touch events a bit unreliable but I can't tell if it's due to p5 or js in general.
