### ISSUE TITLE
passing a height parameter to a circle collider causes sketch error

### ISSUE THREAD

**Issue by lee2sman** [molleindustria/p5.play#154]
Hi, when declaring setCollider with a "circle" if I include a height (in addition to radius/width) then my sketch won't load.

[code](http://alpha.editor.p5js.org/msilliv1/sketches/r1Q-6-Tlz)

Notice sketch won't load and no error message. If you delete the last parameter (delete the last 13 on line 22) then the sketch loads a-ok.

**Comment by lee2sman** [comment]
Just to add some clear feedback, Ideally having an extra 'height' parameter on a circle collider should:
1.  just let it be ignored
2. or throw an error message
3. or use ellipse sizing

**SIMPLE Fix to begin with would be to have very clear info in the Reference that you CANNOT have a height parameter if you declare a circle collider.**

**Comment by islemaster** [comment]
Hi @lee2sman!  Thanks for providing this feedback.  Agreed that this can be improved.

Opening your example code, I see the following error in the Chrome JavaScript console:
```
Uncaught TypeError: Usage: setCollider("circle") or setCollider("circle", offsetX, offsetY, radius)
    at Sprite.setCollider
```
I think that already matches solution #2 you proposed above, but I guess it wasn't very obvious - perhaps because the error didn't show up in the onscreen console for the IDE you are using?  I'm not sure why that is - I've never seen alpha.editor.p5js.org before.

Maybe it would be more user-friendly to log a warning about the extra parameter, then ignore it so the game can proceed.  What do you think?  I'll throw together that change and tag you for review.

**Comment by islemaster** [comment]
Will you take a look at https://github.com/molleindustria/p5.play/pull/155 and let me know if that seems like a good solution to you?

**Comment by lee2sman** [comment]
Excellent solution!

**Comment by islemaster** [comment]
Fix merged to master.  Thanks!
