### ISSUE TITLE
Give P5 Primitives Collision?

### ISSUE THREAD

**Issue by reallyTired** [molleindustria/p5.play#172]
~~Before adding invisible sprites to a vinilla p5 primitive projectile for collision it ran completely fine but adding the new sprite is causing it to slowly lower in frame rate. at first i thought it was my code not properly removing the sprite so i started drawing it and moved the kill line to the middle rather then the very edge so i can see very clearly if they are being removed and they definitely are.~~

EDIT: i probably should stop coding when im tired, i have figured out the performance issue and it was entirely my fault. i had been creating a new sprite for each frame in the most obvious way imaginable like an idiot. oh well ill change my question because i didnt find an answer.

is there any way to give primitives collision without just giving them an invisable sprite?
if not its not an issue just curious

**Comment by islemaster** [comment]
Thanks for your suggestion!  I don't think that's something that makes sense for this library.

My thinking: `p5` shape primitives are drawing commands that affect canvas state but don't store any persistent information about the shape itself, and our existing collision code depends on having some persistent information about the shapes that are colliding.  When I think about approaches I would take to this, two options come to mind.

1. Using existing pixel-matching collisions
   This is generally more expensive than shape-shape collisions so it might be difficult to get it to perform well in a wide variety of situations.  You'd also need to solve the question of which pixels you're matching against - if your canvas is transparent you'd be okay, but if you're doing a background fill or any other more complex graphics you would need some concept of layers to separate out which set of pixels should cause collisions and which ones should not.

2. Primitive draw functions create colliders as a side effect
   This seems more viable but I'd want it to be an opt-in behavior, both because it may violate the principle of least surprise, and because, again, you might want to draw some things and enable collisions and draw other things without collisions.  There's a bigger problem here though, which is that you don't want to end up in exactly the scenario you described above, where you're adding a new sprite every frame for every shape - you'd either need to throw away all of these "automatic" sprites every frame and make new ones, or have some way of tracking and updating the sprites associated with each draw command in your code, which gets into metaprogramming and might be tricky.  That might not be aligned with one of our goals, which is for the library not just to be usable for beginners, but to also be easy-ish to open up and hack on as well.

I can see the appeal though and am glad you brought it up.  I can envision a variant on this tool with a more opinionated world-model that solved the above problems, and made it easy for everything you draw to be interactable - letting you set rules saying all pink shapes are bouncy, or green shapes apply friction to anything moving through them.
