### ISSUE TITLE
Can't use modern ES6 inheritance

### ISSUE THREAD

**Issue by leissler** [molleindustria/p5.play#185]
Since p5.play is based on ES5 code it is not possible to derive an ES6 class from Sprite, which would be very convenient. I'm a C#, C++ and Java developer but don't have much experience with Javascript/ES. Wouldn't it be quite easy to convert the library to a modern ES6 version with classes for Sprite, QuadTree, etc.?

**Comment by GoToLoop** [comment]
The reason the class **_Sprite_** isn't inheritable isn't b/c it's ES5, but b/c its methods aren't stored in its constructor's _prototype{}_.

Which is a bad style b/c methods are re-created each time it's instantiated instead of reusing the 1s defined in its _prototype{}_.

ES6 classes already place methods in the _prototype{}_ btW.

**Comment by leissler** [comment]
So are you saying that it would be rather simple to re-structure the complete library to store methods in constructor prototypes?
When looking into the source code I see helper stuff, like _defineLazyP5Property_ and _createPInstBinder_, which seems to make everything compatible with p5.
So what would it take to make the classes ES6-derivable using _class_ and the _extends_ keyword?

Right now the sprite class looks like this:

```
function Sprite(pInst, _x, _y, _w, _h) {
  var pInstBind = createPInstBinder(pInst);
  var createVector = pInstBind('createVector');
  var color = pInstBind('color');
  var random = pInstBind('random');
  var print = pInstBind('print');
  ...
```
Would it be just something like this?

```
function Sprite(pInst, _x, _y, _w, _h) {
  var pInstBind = createPInstBinder(pInst);
  this.createVector = pInstBind('createVector');
  this.color = pInstBind('color');
  this.random = pInstBind('random');
  this.print = pInstBind('print');
  ...
```

**Comment by GoToLoop** [comment]
> So are you saying that it would be rather simple to re-structure the complete library to store methods in constructor prototypes?

B/c the library relies on many complex "hacks", it's not gonna be that simple!

> ... I see helper stuff, like **defineLazyP5Property()** and **createPInstBinder()**, which seems to make everything compatible with p5.

I've got my doubts whether those are actually needed for p5js compatibility. Maybe some are, but not all.

> So what would it take to make the classes ES6-derivable using `class` and the `extends` keywords?

Like I've stated in my 1st reply: "but b/c its methods aren't stored in its constructor's _prototype{}_."

That is, we have to move all properties storing the **_Sprite_**'s methods outside its constructor and store them in its _prototype{}_ instead.

So regular properties stay inside its constructor though.

However, the **_Sprite_**'s constructor got lotsa local variables acting as closures for its methods.

So we've gotta make sure to turn such closures into properties instead, so they're also accessible outside its constructor.

As an initial refactoring, let's turn **_Sprite_**'s internal method **draw()** as an external _prototype{}_ method:
https://GitHub.com/molleindustria/p5.play/blob/master/lib/p5.play.js#L1680-L1695
```js
  * @method draw
  */
  this.draw = function()
  {
    if(currentAnimation !== '' && animations)
    {
      if(animations[currentAnimation])
        animations[currentAnimation].draw(0, 0, 0);
    }
    else
    {
      noStroke();
      fill(this.shapeColor);
      rect(0, 0, this._internalWidth, this._internalHeight);
    }
  };
```
Just in the above method, we've got 5 closure variables already!

2 of them are **_Sprite_**'s local variables: _animations{}_ & _currentAnimation$_.

While the other 3 are actually **_p5_**'s methods: **noStroke()**, **fill()** & **rect()**.

For the **_Sprite_**'s local variables case, we simply convert them to properties:
`this.animations = {}; // var animations = {};`
`this.currentAnimation = ''; // var currentAnimation = '';`

For the **_p5_**'s methods case, we create a **_Sprite_** property which stores the **_p5_**'s reference:
`this.p = pInst; // var pInstBind = createPInstBinder(pInst);`

Here's the "full" demo I've come up w/:
```js
function Sprite(pInst, _x, _y, _w, _h) { // ES5 function constructor
  this.p = pInst; // var pInstBind = createPInstBinder(pInst);
  this.animations = {}; // var animations = {};
  this.currentAnimation = ''; // var currentAnimation = '';
}

Sprite.prototype.draw = function () { // prototype{} method
  if (this.animations && this.currentAnimation) {
    var currAnim = this.animations[this.currentAnimation];
    currAnim && currAnim.draw(0, 0, 0);
  } else {
    this.p.noStroke().fill(this.shapeColor);
    this.p.rect(0, 0, this._internalWidth, this._internalHeight);
  }
};

class MySprite extends Sprite { // ES6 subclass
}

function setup() { // p5's callback function
  // Method draw() got inherited b/c it's inside Sprite's prototype{} now:
  print(new MySprite(this, width>>2, height>>2, width>>1, height>>1).draw);
}
```

**Comment by leissler** [comment]
When starting a refactoring, shouldn't it be ES6 classes then right away?
Like so

```es6
class Sprite {
  constructor(_x, _y, _w, _h) { // ES6 constructor
    this.animations = {}; // var animations = {};
    this.currentAnimation = ''; // var currentAnimation = '';
  }

  draw() { // prototype{} method
    if (this.animations && this.currentAnimation) {
      let currAnim = this.animations[this.currentAnimation];
      currAnim && currAnim.draw(0, 0, 0);
    } else {
      p5.noStroke().fill(this.shapeColor);
      p5.rect(0, 0, this._internalWidth, this._internalHeight);
  }
};

class MySprite extends Sprite { // ES6 subclass
}

function setup() { // p5's callback function
  // Method draw() got inherited b/c it's implicitly placed 
  // inside Sprite's prototype{} now:
  print(new MySprite(this, width>>2, height>>2, width>>1, height>>1).draw);
}

```
With p5 being some kind of global shared reference to the p5 context.

**Comment by GoToLoop** [comment]
> When starting a refactoring, shouldn't it be ES6 classes then right away?

Yup! A true overhaul should include a conversion from ES5 constructor functions to ES6 classes.

I've left **_Sprite_** still using the ES5 style just to make a point the problem had nothing to do w/ ES5 per se.

> With _p5_ being some kind of global shared reference to the **_p5_** context.

Man, this is doubly über wrong!

1st of all, _p5_ is already a global variable added by "p5.js" library storing the reference to its main class **_p5_**.

Therefore it refers to a constructor function (class), not an instance object of that.

Secondly, we've got 2 modes in p5.js.
- Global Mode: https://p5js.org/examples/structure-setup-and-draw.html
- Instance Mode: https://p5js.org/examples/instance-mode-instantiation.html

Your refactored **_Sprite_** class would surely fail to work w/ the 2nd example b/c the **_p5_** methods wouldn't be globally available anymore!

Here's a very basic sketch example using the p5.play library under the p5.js instance mode approach:
- https://Bl.ocks.org/GoSubRoutine/cf739128f389766f5d9cb631c9c358a6
- https://Gist.GitHub.com/GoSubRoutine/cf739128f389766f5d9cb631c9c358a6

So, we can have at most 1 global mode sketch in the same _window_ page.

However, we can have as many instance mode sketches in the same _window_ page together w/ up 1 global mode sketch!

Having more than 1 sketch running in the same _window_ page, how would the p5.play library know which canvas to interact w/ if not by requesting 1 of those **_p5_** references?

Thus in order for the p5.play library to continue to work w/ the p5.js library regardless which mode style its sketch is using, we have to request & store a **_p5_** reference from a sketch:
```js
class Sprite {
  constructor(p5Inst, _x, _y, _w, _h) {
    this.p = p5Inst;
    this.animations = {};
    this.currentAnimation = '';
  }

  draw() {
    if (this.currentAnimation) {
      const currAnim = this.animations[this.currentAnimation];
      currAnim && currAnim.draw(0, 0, 0);
    } else {
      this.p.noStroke().fill(this.shapeColor);
      this.p.rect(0, 0, this._internalWidth, this._internalHeight);
    }
  }
}
```

**Comment by GoToLoop** [comment]
BtW, here's a previous issue about how the "p5.play" library became compatible w/ "p5.js" instance mode:
https://github.com/molleindustria/p5.play/issues/12

**Comment by molleindustria** [comment]
I mostly use C# as well and it would be great to refactor p5.play to allow extendable classes and instance mode. ES6 was not on my radar when I started it and the idea was to make the library understandable to students who don't know OOP yet. ie if you want to make a sprite subclass you can just make a sprite and add a bunch of properties and methods dynamically since in js anything goes. 
(I'm generally unfazed by efficiency issues because in my experience the canvas rendering always seems to take like 99% of the processing power anyway)

**Comment by leissler** [comment]
Hey, how about that?! We got the developers attention here :)
I'm a professor at a University in Germany and teaching game development over here. Besides missing a tile library and not being designed as OOP as it could be, I really like p5.play for teaching the basics of programming interactive applications and games.
So would you endeavor into converting it to ES6 classes, making it more C# and OOP style, while still having the benefits of JavaScript? That would help quite a bit in bridging between C++/C# and JavaScript. 
Like in many game engines/frameworks, it's just my opinion that code e.g. for collisions should be handled within an onCollision method within a Sprite-derived object, every Sprite-derivative should have its own update() and draw() methods and so on. Also using the Sprite constructor should initialize a standard Sprite, not a global createSprite() function. But this last part is just opinion of design choice.
Would love to hear your opinion.

**Comment by ejgutierrez74** [comment]
Hi, any progress here ? Would be nice to have ES6 classes compatible with p5.play

**Comment by quinton-ashley** [comment]
@ejgutierrez74 I've just made a lot of progress on this! I will send a push request to @molleindustria but I doubt they will see it or accept it for a long time since they seemed pretty inactive until 2 months ago. I'll make my own repository and make an npm package for the new ES6 version of p5.play

**Comment by quinton-ashley** [comment]
@molleindustria I really like your p5.play library btw! Here's a bit of background about why I wanted to do this.

I'm a computer science teacher and my students have used it (via QuintOS which simplifies p5.play to make it easier to use for young students) to make some great games :) You can see them on https://quintos.org/home.html

I realized yesterday that the way I was extending Sprite was not optimal (adding methods to each sprite object which I realized you did as well) and then I realized because of that I actually couldn't extend the Sprite class or (effectively) add methods to the prototype.

I want to change a lot about how my simplified p5.play functions work in QuintOS under the hood and add additional functionality so I thought I should start by converting p5.play itself to ES6.

**Comment by molleindustria** [comment]
@quinton-ashley Well my background is that p5 was my way to use javascript without dealing with the disgusting world of modern javascript development and p5.play an attempt to give my art students who don't know how to code a simple way to display something more than squares and lines. Then a bunch of real js developers got on board on the library and added all this stuff I don't understand nor care to learn, so I haven't updated anything since my first commit in 2015. I don't even have the repository on my machine. I digress but this is the long answer to why there is no ES6: I don't even know what it is.
Welcome aboard!

**Comment by quinton-ashley** [comment]
@molleindustria Thanks! Luckily I think the change to ES6 classes actually makes the code a lot easier to understand, especially for newer JS developers. JavaScript was not such a good language in my opinion before they added async/await (fixed callback stack hell) and ES6 classes which made it a lot easier to extend classes with inheritance instead of just with adding functionality to an Object's prototype. Also I totally get the motivation for making this library to enable more complex game development using p5.js, it's really good.

Anyways here is my pull request!

https://github.com/molleindustria/p5.play/pull/215

**Comment by quinton-ashley** [comment]
@molleindustria Thanks for adding me as a contributor! I will make some other fixes and additions to p5.play as well.

My changes solve the issue, closing this issue. 🎉

**Comment by quinton-ashley** [comment]
@molleindustria it's funny you don't even have the repo on your machine lolz It must be a lot of work to maintain a repository like this. I've helped you out responding to and closing some issues and outdated pull requests requests. :)

**Comment by molleindustria** [comment]
@quinton-ashley That's amazing, thank you so much. And yes, most of the maintenance and fixes were made by two other contributors in 2016-17. I barely touched anything since the launch.
