### ISSUE TITLE
Is it possible to collide Sprite with Collider of other Sprite object ?

### ISSUE THREAD

**Issue by ejgutierrez74** [molleindustria/p5.play#201]
Think we have a ball and player tennis. My idea is that tennis ball would have to colliders. Right collider and left collider ( as name suggests right collider would be a circle from center to the right ( half rightof the ball), the other collider would be the left part of the ball.
I would liket to test something like:
tennisplayer,collide ( ball.rightcollider , reboundright);
tennisplayer,collide ( ball.left.collider , reboundleft);

The idea is that player collider with left collider of tennis ball the ball would go to the left and right part off the ball to the ritght. Perhpaps could add a third collider in the center of the ball, and ten  return ball in center direction.

Thanks

**Comment by quinton-ashley** [comment]
Make separate sprites for the tennis player if you only want the bounce to be straight center, diagonal left, and diagonal right. 

Otherwise if you want the ball to bounce of the sprite at an angle controlled by the player's angle, make the ball collider a circle collider and it will bounce at whatever angle the player rectangle is rotated to.

Closing this issue.
