### ISSUE TITLE
Add an npm task to generate the documentation

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#41]
I have no idea how to regenerate the reference documentation for this project.

It would be great if we had an `npm docs` command or something that rebuilt them.

It would be *really* cool if `npm start` also rebuilt the docs whenever changes were made to `lib/p5.play.js`, but I suspect this would require adopting grunt or gulp (I prefer gulp, but we can use grunt if we want to maintain parity with p5.js development).

We might also want to consider removing the built docs from the repository, so that we don't need to spam the commit history with rebuilds of the documentation whenever we change it.

**Comment by islemaster** [comment]
I've got a WIP on my [yuidoc-helper branch](https://github.com/molleindustria/p5.play/compare/master...islemaster:yuidoc-helper).

**Comment by islemaster** [comment]
There are a lot of asks in this one issue, but #45 resolved the ask in the title.  The remaining asks seem to be:

* Work with @molleindustria to update the docs at p5play.molleindustria.org/docs
* Somehow automate docs generation, so that a hosted version somewhere is always current with `master`
* Remove the built docs from the repository (presumably after the above work)
* Provide a watcher for the local docs build (I question the usefulness of this :wink:)

@toolness do you think we should:

* Rename this issue to reflect the remaining asks and clarify what's left?
* Resolve this issue and open new ones for the remaining work?

**Comment by toolness** [comment]
Oh, sorry I didn't reply to this!

Hmm, I think we should resolve this issue and open new ones, because resolving issues is fun, and also because I was half-daydreaming when I wrote this issue :grin:
