### ISSUE TITLE
Use 'init' registerMethod() instead of lazily-setting properties

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#46]
Some complexity in supporting instance mode was introduced because there wasn't a way for extension libraries to do initialization when a sketch is first created. This resulted in us having to create a function called `defineLazyReadOnlyP5Property()`, among other things. Some discussion about the complexity is at https://github.com/molleindustria/p5.play/pull/22#discussion_r53211269.

Anyways, since then, I've contributed a new `'init'` `registerMethod()` type to core p5 in https://github.com/processing/p5.js/pull/1291, so going forward, we could potentially use that instead of `defineLazyReadOnlyP5Property()`, which could simplify p5.play's internals a bit.

**Comment by quinton-ashley** [comment]
Interesting, I will look into this.

**Comment by quinton-ashley** [comment]
@toolness I finished what you started and completed this in v2.1.3 :)

**Comment by quinton-ashley** [comment]
@toolness Actually I noticed that doing it that way only kind of worked but `instanceof` did not work because each class was essentially being turned into a separate function which made all the work I did turning them into classes (for better performance) pointless. I improved upon it by putting all the classes inside the `p5PlayInit` function and then storing `this` (the p5 instance) in a variable `pInst` which I could then use inside the classes. It took me a while to figure out but now `instanceof` works.

**Comment by quinton-ashley** [comment]
@toolness v2.2.0 is ready!

**Comment by CyberSix6** [comment]
new at this, please refer to open ones.

**Comment by quinton-ashley** [comment]
@CyberSix6 what?
