### ISSUE TITLE
Group.removeSprites does not remove all sprites?

### ISSUE THREAD

**Issue by KouichiMatsuda** [molleindustria/p5.play#7]
The following codes remains two sprites.
Am I missing something?
```javascript
// Group
var pumpkins;

function setup() {
  createCanvas(300, 300);
  pumpkins = new Group();
  for(var i = 0 ; i < 5 ; i++){
    var sprite = createSprite(random(0, width), random(0, height / 2)); 
    sprite.velocity.y = 1; 
    pumpkins.add(sprite);
  }
}

function draw() {
  background(255);
  drawSprites();
}

function mouseClicked() {
   pumpkins.removeSprites();
}
```

The following "removeSprites" code in p5.play.js looks fine.
("@method clear" should be "@method removeSprites")
```javascript
  /**
  * Removes all the sprites in the group
  * from the scene.
  *
  * @method clear
  */
  array.removeSprites = function() {
    
    for(var i = 0; i<array.length; i++)
      array[i].remove();
    
    array.length = 0;
  }
```

**Comment by alexrus07** [comment]
If it still matters, I managed to achieve total removal of sprites in a group by using a do/while loop, like this:

```
do {
          trees[0].remove();
        } while(trees[0] !== undefined)
```

**Comment by KouichiMatsuda** [comment]
Thanks. But do you know the reason why the following does not work?

  ```javascript
array.removeSprites = function() {
    for(var i = 0; i<array.length; i++)
      array[i].remove();

    array.length = 0;
  }
```

**Comment by alexrus07** [comment]
It doesn't work because JavaScript shifts array elements after you remove one from it. So if you remove element at position 0, the element that was previously in position 1 will now be in position 0. So if you increment your count by 1 for every pass in the for loop, you will essentially skip over every second element in the array.

The removeSprites() function is wrong in p5.play and its probably a good idea to report this bug to the developers.

I hope my explanation makes sense :)

Date: Thu, 15 Oct 2015 05:37:02 -0700

**Comment by GoToLoop** [comment]
Assuming method **remove()** returns the object being removed, this is a much shorter version:
`while (trees[0].remove());`

However, a more performance way to do it is a backwards loop, since it avoids the left shifting:
`for (var i = trees.length; i--; trees[i].remove());`

**Comment by KouichiMatsuda** [comment]
@alexrus07 
oh, i see. thanks a lot.
